
language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - wget http://dl.dropboxusercontent.com/u/90405495/resources.zip
  - wget http://dl.dropboxusercontent.com/u/90405495/resources-extra.zip
  - unzip resources.zip -d resources
  - unzip resources-extra.zip -d resources

script: python tests.py

sudo: false
notifications:
  email: false
